import sympy as sp
from sympy import sstr
from itertools import product

def invariants(n, d, chi, init):
    # ---------------------------------------
    # Generate divergence variables Y1,...,Yn
    # ---------------------------------------
    # Generate variables Y1,...,Yn and store them as a SymPy Matrix.
    Y = sp.symbols(f'Y1:{n+1}') 
    Y = sp.Matrix(Y)

    # ------------------------------
    # Generate the monomial vector M
    # ------------------------------
    M = []
    for p in range(d + 1):
        # Compute the monomials Y1^j1*...*Yn^jn, where exp = (j1, ..., jn) ranges over 
        # {(j_1, ..., j_n) | sum_{i=1}^n j_i = p}, and store the result in M. 
        for exp in product(range(p + 1), repeat=n):
            if sum(exp) == p:
                # Reverse the exponent vector so that the first exponent corresponds to Y1.
                mon = sp.prod(Y[i] ** j_i for i, j_i in enumerate(reversed(exp)))
                M.append(mon)
    M = sp.Matrix(M) 
    # m is the number of monomials in the polynomial invariant of degree d in n variables
    m = len(M)

    # ---------------------------
    # Generate divergence vectors 
    # e0,...,em-1
    # ---------------------------
    e = [sp.Matrix(init)]
    # The initial divergence vector is e0 = init  
    # By definition, e_i = chi(e_{i-1}) for i = 1,...,m-1
    for i in range(1, m):
        e.append(chi(e[i - 1]))

    # ------------------------------------
    # Generate divergence matrix D:
    # Row i of D equals M evaluated in e_i
    # ------------------------------------
    D = sp.zeros(m, m)  # preallocate an m x m symbolic matrix

    for i in range(m):
        # Construct a dictionary: mapping Y[j] to e_i[j], for all j
        subs_dict = {Y[j]: e[i][j] for j in range(n)}

        # Use the dictionary to evaluate each monomial in M at e_i to obtain row i of D.
        for col, mon in enumerate(M):
            D[i, col] = mon.subs(subs_dict)


    # ------------------------------------------------
    # Print result together with important information
    # ------------------------------------------------
    print(f"Polynomial degree: d = {d} ")
    print("Initial vector: e0 =",
      [sp.simplify(e) for e in init])
    print("Divergence variables:", ", ".join(str(y) for y in Y))
    print(f"Divergence substitution: chi({', '.join(str(y) for y in Y)}) =")
    chiY = chi(Y)
    sp.pprint(chiY)
    print("Monomial vector: M = [", ", ".join(sstr(m).replace("**", "^") for m in M), "]")
    print("\nDivergence matrix: D = ")
    sp.pprint(D)

    # -------------------------
    # Compute kernel and invariants
    # -------------------------
    print("\nker(D) is generated by the following vectors:\n")
    B = D.nullspace()
    for b in B:
        sp.pprint(b)
        print()

    print("This corresponds to the following polynomial invariants:\n")
    Invariants = []
    for b in B:
        inv = sum(b[i] * M[i] for i in range(m))
        eq_str = sp.pretty(sp.expand(inv)) + " = 0" 
        Invariants.append(sp.expand(inv)) 
        print(eq_str)


    return Invariants


# =====================================================
# Calling the invariant function with the desired input
# =====================================================

# ------------------------
# Divergence substitution
# ------------------------
# The user-defined chi is expected to use 1-based indexing for the divergence
# variables (i.e. Y[1], ..., Y[n], rather than Python's standard Y[0], ..., Y[n-1]) to match the mathematical notation V_div = {Y1,...,Yn} used in the paper.
def chi(Y):
    return sp.Matrix([
        Y[1] - 1,
        Y[2] + Y[1], 
        Y[3] + Y[1]
    ])

# Convert a user-defined 1-based substitution to the 0-based indexing (as expected internally by Python).
def index_zero_shift(chi_1based):
    def chi_0based(Y_0based):
        # Y_0based[0] corresponds to Y1, 
        # Y_0based[1] corresponds to Y2, etc.
        # Convert Y_0based to a 1-based list by adding a first dummy element None, and use it as input to chi_1based.
        Y_1based = [None] + list(Y_0based)
        result = chi_1based(Y_1based)
        return sp.Matrix(result)
    return chi_0based




if __name__ == "__main__":
# ------------------------
# Initialization variables
# ------------------------
    x = sp.symbols('x')
   
# -------------- 
# Initial vector 
# --------------
    e0 = sp.Matrix([x-1, x, 0])

# ------------------------------
# Number of divergence variables
# ------------------------------
    n = 3

# -----------------
# Polynomial degree
# -----------------
    d = 1
    
# ----------------------------------------------------
# Calling the invariants function on the desired input
# ----------------------------------------------------
    Invariants = invariants(n, d, index_zero_shift(chi), e0)
